### ISSUE TITLE
Atheros Card used for Sample File

### ISSUE THREAD

**Issue by niklasser** [xieyaxiongfly/Atheros-CSI-Extraction-TOOL-UserSpace-APP#15]
Hello @xieyaxiongfly,
can you tell me which card you used to record the sample file (sample_bigEndian.dat).
I currently have two WiFi Nic's with an Atheros 9344 running OpenWrt. When im recording CSI information, my phase angles are all over the place. With your sample file this is not the case, the phase angles behave as expected. 

Niklas

**Comment by xieyaxiongfly** [comment]
I use Atheros 9580. Maybe you can check that card.
