### ISSUE TITLE
read_csi.c error

### ISSUE THREAD

**Issue by junsujang** [xieyaxiongfly/Atheros-CSI-Extraction-TOOL-UserSpace-APP#35]
I was able to get a CSI data using the tool. However, when I try to use MATLAB code provided, it complains as follows. I initially thought that this was an error due to my mac computer, but I ran this again on linux, but same error has occured. Has anyone experienced this before? I am currently using MATLAB 2017a

Error using read_csi
Requested 4294967299x140673063845944x140675699690528
(17179869184.0GB) array exceeds maximum array size preference.
Creation of arrays greater than this limit may take a long time and
cause MATLAB to become unresponsive. See array size limit or
preference panel for more information.

I also tried running using the read_csi.mexa64 provided by the UserSpace code, and it just crashed the matlab.

**Comment by junsujang** [comment]
I have figured out the first problem. 

When calling mxCreateNumArrray(ndims, dim, class, complex), dims is of type (size_t *). The array "size" was not of correct type, and I was getting an undefined behavior from MATLAB.

However, as I run it, I still have MATLAB crash due to segmentation fault that I cannot track...

UPDATE: 
I realized that the data that I collected are showing weird behaviors. I am unsure as to why the rssi values are different on all the samples. From previous experience, the first set of data seem reasonable but afterwards, rssis and payloads don't seem to make sense at all. Could there be a problem at recv_csi end? Also please have a look at err_info values...

file length is:1642496
Block length is:52485
timestamp is 4869265764198121472
csi_len is 41985
channel is 34057
err_info is 0
noise_floor is 0
rate is 87
bandWidth is 0
num_tones is 56  nr is 3  nc is 1
rssi is 57
rssi1 is 54
rssi2 is 39
rssi3 is 54
payload length: 4100

Block length is:135
timestamp is 15765902485497654
csi_len is 4100
channel is 37083
**err_info is 255**
noise_floor is 254
rate is 25
bandWidth is 250
num_tones is 215  nr is 144  nc is 56
rssi is 253
rssi1 is 246
rssi2 is 147
rssi3 is 146
payload length: 65293

Block length is:43690
timestamp is 1.229783e+19
csi_len is 43690
channel is 43690
**err_info is 170**
noise_floor is 170
rate is aa
bandWidth is 170
num_tones is 170  nr is 170  nc is 170
rssi is 170
rssi1 is 170
rssi2 is 170
rssi3 is 170
payload length: 43690

**Comment by shuspieler** [comment]
you remove this line from the recvCSI and run 'make'.

https://github.com/xieyaxiongfly/Atheros-CSI-Tool-UserSpace-APP/blob/38a2f47a95ca39ec90794a883e0623a2bf0ac407/recvCSI/main.c#L80

then use the updated binary to receive CSI data.
and try again.

**Comment by junsujang** [comment]
Unfortunately, I still face the same issue... 
The difference is that I can process more than 3 samples compared to last time, but on the second data, I still obtain err_info: x, where x is non-zero

**Comment by junsujang** [comment]
The problem was with read_log_file.m. My system was using little endian, and 
`endian_format = 'ieee-be';` needed to be changed to `endian_format = 'ieee-le';`

Also, MATLAB was not able to parse upto proper field_len, so I had to add in some customization.
