### ISSUE TITLE
Why the number of antennas is not corresponding to CSI matrix?

### ISSUE THREAD

**Issue by hanstseng123** [xieyaxiongfly/Atheros-CSI-Extraction-TOOL-UserSpace-APP#48]
I use TP-link wdr4300 as AP and client. And I set 3 antennas and 1 antenna on AP and client respectively.
But my CSI matrix is 2*2*56.
I also try 1  antenna on both AP and client, but I still get CSI as 2*2*56 matrix. 

CSI data from condition of AP and client both with 1 antenna.  
![image](https://user-images.githubusercontent.com/37927874/44247123-cac8c100-a214-11e8-9bc0-d324cd034b1b.png)
CSI data from condition of AP with 3 antennas and client with 1 antenna.  
![image](https://user-images.githubusercontent.com/37927874/44247152-ed5ada00-a214-11e8-9ae8-9515b6505048.png)

Did anyone meet this problem?

**Comment by shulinyang** [comment]
你解决这个问题了吗，原因是什么？如何修改？感谢@hanstseng123

**Comment by hanstseng123** [comment]
我是更改router設定
透過更改/etc/config/wireless檔案的option
我增加了option txantenna 跟 option rxantenna 更改為使用指定的天線
然後把option diversity '1' 改為option diversity '0'
