### ISSUE TITLE
Converting COMPLEX matrix to SNR values

### ISSUE THREAD

**Issue by brunosoaresds** [xieyaxiongfly/Atheros-CSI-Extraction-TOOL-UserSpace-APP#7]
@xieyaxiongfly 

Hi, in all papers i read, people are using the SNR of CSI to make the job. However i'm not finding how to convert the complex to SNR, can you help me?

Best Regards.

**Comment by xieyaxiongfly** [comment]
Hi there,
For this part, you can borrow the idea of another CSI tool build for Intel 5300. That tool has the code for such functionality.

**Comment by brunosoaresds** [comment]
Thanks :)
